name: Download video

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the video to download'
        required: true

jobs:
    download-video:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            
            
    
        